[package]
name = "ebur128-stream"
version = "0.1.0"
edition = "2024"
authors = ["Kitaiti Makoto <KitaitiMakoto@gmail.com>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.8.2", features = ["rb-sys"] }
rb-sys = { version = "0.9", features = ["stable-api-compiled-fallback"] }
ebur128-stream-rs = { package = "ebur128-stream", version = "0.2.0", features= ["normalize"] }

[build-dependencies]
rb-sys-env = "0.2.2"

[dev-dependencies]
rb-sys-test-helpers = { version = "0.3.0" }
