# frozen_string_literal: true

require "rubygems/tasks"
require "rake/testtask"

Gem::Tasks.new

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

require "rb_sys/extensiontask"

task build: :compile

GEMSPEC = Gem::Specification.load("ebur128_stream.gemspec")

RbSys::ExtensionTask.new("ebur128_stream", GEMSPEC) do |ext|
  ext.lib_dir = "lib/ebur128_stream"
end

task default: %i[compile test]
