# frozen_string_literal: true

require "rubygems/tasks"
require "rake/testtask"

Gem::Tasks.new

Rake::TestTask.new

require "rb_sys/extensiontask"

task build: :compile

GEMSPEC = Gem::Specification.load("ebur128_stream.gemspec")

RbSys::ExtensionTask.new("ebur128_stream", GEMSPEC) do |ext|
  ext.lib_dir = "lib/ebur128_stream"
end

task default: %i[compile test]
